core/core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('iol.urls')),
    path('accounts/', include('accounts.urls')),
    path('sort/', include('sorting.urls')),
    path('dash/', include('dashboard.urls')),


]

core/iol/urls.py
from django.urls import path, re_path
from . import views
from .views import ModuleListView, IolistView
from django.contrib.auth.decorators import login_required

urlpatterns = [

    ###
    path('add_signals/', views.add_signals, name= 'add_signals'),
    path('projects/create/', views.create_project, name='create_project'),
    path('project_list', views.project_list, name='project_list'),
    path('', views.home, name='home'),
    path('projects/<int:project_id>/', views.project_detail, name='project_detail'),
    path('get_signals/<int:module_id>/', views.get_signals_for_module, name='get_signals'),
    path('get_filtered_signals/', views.get_filtered_signals, name='get_filtered_signals'),
    path('toexcel/', views.export_to_excel, name= "to-excel"),



    #To manage modules & signals

    path('module_list/', ModuleListView.as_view(), name='module_list'),
    path('create_module/', views.create_module, name='create_module'),
    path('module_list/<int:id>/delete/', views.module_destroy, name='module_delete'),
    path('edit_module/<int:module_id>/', views.edit_module, name='edit_module'),

    #Delete signal while adding
    path('delete_signal/<int:pk>/', views.delete_IO, name='delete-signal'),

    path('iolist_project/<int:project_id>', views.iolist_project, name='iolist_project'),
    re_path(r'^iolist/(?:(?P<pk>\d+)/)?(?:(?P<action>\w+)/)?',  login_required(views.IolistView.as_view()), name='iolist'),
    re_path(r'^signals/(?:(?P<pk>\d+)/)?(?:(?P<action>\w+)/)?',  login_required(views.ClusterView.as_view()), name='signals'),
]

core/iol/models.py
from django.db import models
from django.db.models.base import ModelBase
from django.contrib.auth.models import User
from django.db.models.signals import post_save

from django.dispatch import receiver



Segments=(('Carton/Tote Handling','Carton/Tote Handling'),
          ('Slit Roll','Slit Roll'),
          ('CBS', 'CBS'),
          ('Robotics','Robotics'),
          ('ASRS-MB','ASRS-MB'),
          ('ASRS-Stacker','ASRS-Stacker'))
ChoicesPLC=(('Siemens','Siemens'),
            ('Allen Bradley', 'Allen Bradley'),
            ('Mitsubishi', 'Mitsubishi'))
            

class Project(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=500, blank=True)
    segment = models.CharField(max_length=50, blank=True, default =Segments[0][0], choices = Segments)
    created_by = models.CharField(max_length=30)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField()
    is_Murr = models.BooleanField(default=False)
    isFreeze = models.BooleanField(default=False)
    PLC = models.CharField(max_length=50, default='Siemens', choices = ChoicesPLC)
    panels = models.JSONField(blank=True, null=True)
    panel_numbers = models.CharField(max_length=1000, blank=True, null=True)
    exported_at = models.DateTimeField( blank=True, null=True)
    exported_by = models.CharField(max_length=30, blank=True, null=True)

    # segment = models.CharField(max_length=50, blank=True, default =Segments[0][0], choices = Segments)

    def __str__(self):
        return self.name

class CountryManager(models.Manager):
    """Enable fixtures using self.sigla instead of `id`"""

    def get_by_natural_key(self, module):
        return self.get(module=module)

class Module(models.Model):
    module = models.CharField(max_length=50)
    description = models.TextField(max_length=500, blank=True)
    created_by = models.CharField(max_length=30)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    segment = models.CharField(max_length=50, blank=True, default =Segments[0][0], choices = Segments)
    def __str__(self):
        return self.module

class IOList(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    equipment_code = models.CharField(max_length=30)
    code = models.CharField(max_length=40)
    tag = models.CharField(max_length=100, editable=True)
    signal_type = models.CharField(max_length=10)
    device_type = models.TextField(max_length=100, blank=True)
    actual_description = models.TextField(max_length=200)
    panel_number = models.CharField(max_length=10, blank=True, null=True, default='CP01') #models.CharField(max_length=30, choices=[(k, k) for k in project.panel_keys]) 
    node = models.CharField(max_length=10, blank=True, null=True)
    rack = models.IntegerField(blank=True, null=True)
    module_position = models.IntegerField(blank=True, null=True)
    terminal_block = models.CharField(max_length=5, blank=True, null=True)
    terminal_number = models.IntegerField(blank=True, null=True)
    channel = models.IntegerField( blank=True, null=True)
    location = models.CharField(max_length=2, choices=(('FD', 'FD'), ('CP', 'CP')), default='CP')
    io_address = models.CharField(max_length=20, blank=True, null=True)
    Cluster = models.CharField(max_length=50, default="Testing")
    created_by = models.CharField(max_length=30)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    order = models.PositiveIntegerField(null=True)
    cluster_number = models.PositiveIntegerField(null=True)
    Demo_3d_Property = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.tag
    
    class Meta:
        ordering = ['order']


class Signals(models.Model):
    equipment_code = models.CharField(max_length=30)
    code = models.CharField(max_length=40)
    component_description = models.TextField(max_length=100, blank=True)
    function_purpose = models.TextField(max_length=100, blank=True)
    device_type = models.TextField(max_length=100, blank=True)
    signal_type = models.CharField(max_length=10, default="DI", choices=(('DI', 'DI'), ('DO', 'DO'), ('Encoder', 'Encoder')))
    remarks = models.TextField(max_length=100, blank=True)
    segment = models.CharField(max_length=50, blank=True,default=Segments[0][0], choices = Segments)
    initial_state = models.BooleanField(default=True)
    location = models.CharField(max_length=2, choices=(('FD', 'FD'), ('CP', 'CP')))
    module = models.ForeignKey(Module, on_delete=models.CASCADE,default= 1, related_name = "modules")
    created_by = models.CharField(max_length=30)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    Demo_3d_Property = models.CharField(max_length=200, blank=True, null=True)
    def __str__(self):
        if self.equipment_code != '':
            return f'{self.equipment_code}_{self.code}'
        else:
            return self.code

# @receiver(post_save, sender=Project)
# def create_profile(sender, instance, **kwargs):

class ProjectReport(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    updated_at = models.DateTimeField(blank=True, null=True)
    updated_by = models.CharField(max_length=50,blank=True, null=True)
    created_at = models.DateTimeField()
    created_by = models.CharField(max_length=50,blank=True, null=True)
    segment = models.CharField(max_length=50, blank=True, default =Segments[0][0], choices = Segments)

    def __str__(self):
        return str(self.project)


@receiver(post_save, sender=Project)
def create_project_report(sender, instance, created, **kwargs):
    if created:
        ProjectReport.objects.create(
            project=instance,
            created_at=instance.created_at,
            created_by=instance.created_by,
            segment = instance.segment,
            # You can set exported_at and exported_by based on your requirements
        )

core/templates/update_data/cluster_signals.html
{% extends 'base/base.html' %}
{% load static%}
{% block title %}<title>{{ module }} Signals</title>{% endblock %}
{% block script %}
<script src="{% static 'js/tables.js' %}"></script>
{% endblock %}
{% block content %}


  <div class="panel panel-primary filterable text-center mx-auto">
    <div class = "container-flex">
      
      
      <div class="panel-heading d-flex align-items-center">
        <button class="btn btn-primary mt-3 mybtns mr-auto" id="FilterON">
            <span class="glyphicon glyphicon-filter"></span>Click To Apply Filter
        </button>
        <div class="text-center mx-auto float-left">
            <h5 class="card-title mt-3 " id ="Module_Name">{{ module }}</h5>
            <p class="card-text">{{ module.description }}</p>
        </div>
        <a href="{% url 'signals' action='add' %}" class="btn mt-3 ml-auto btn-block btn-secondary">Add Signal</a>
      </div>
    </div>
    
    

  <table class=" table-striped  iotable table" id='example'>
    <thead>


      <tr class="filters">
        <th><input type="text" class="form-control" placeholder="#" disabled></th>
        <th><input type="text" class="form-control" placeholder="Equipment Code" disabled></th>
        <th><input type="text" class="form-control" placeholder="Code" disabled></th>
        <th><input type="text" class="form-control" placeholder="Component Description" disabled></th>
        <th><input type="text" class="form-control" placeholder="Function Purpose" disabled></th>
        <th><input type="text" class="form-control" placeholder="Signal Type" disabled></th>
        <th><input type="text" class="form-control" placeholder="Device Type" disabled></th>
        <th><input type="text" class="form-control" placeholder="Location" disabled></th>
        <th><input type="text" class="form-control" placeholder="Cluster" disabled></th>
        <th><input type="text" class="form-control" placeholder="Initial State" disabled></th>
        <th><input type="text" class="form-control" placeholder="Created By" disabled></th>
        <th><input type="text" class="form-control" placeholder="Created At" disabled></th>
        <th>--</th>
        <th>--</th>
      </tr>
    </thead>
    <tbody>
      {% for signal in signal_list %}
      <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ signal.equipment_code }}</td>
        <td>{{ signal.code }}</td>
        <td>{{ signal.component_description }}</td>
        <td>{{ signal.function_purpose }}</td>
        <td>{{ signal.signal_type }}</td>
        <td>{{ signal.device_type }}</td>
        <td>{{ signal.location }}</td>
        <td>{{ signal.module }}</td>
        <td>
          <input type="checkbox" name="initial_state" class="form-control" 
          id="id_initial_state" {% if signal.initial_state %}checked{% endif %}>
        </td>
        <td>{{ signal.created_by }}</td>
        <td>{{ signal.created_at }}</td>
        <td>
          <a href="{% url 'signals' signal.id 'edit' %}" class="btn btn-sm btn-block btn-warning">Edit</a> 
        </td>
        <td>
          <a href="{% url 'signals' signal.id 'delete' %}" class="btn btn-sm btn-block btn-danger">Delete</a> 
        </td>
      </tr>
      {% empty %}
      <tr>
        <td colspan="5">No iolists found.</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <p>No.of Rows : <span id="rowcount"></span></p>
</div>

</div>

<script>
 

    {% comment %} $('#example').DataTable({
      //Datatable configurations
      paging: true, //Pagination
      pageLength: 10, //Entries per page
      lengthChange: true, //Show entries control for per page
      autoWidth: true, // Control auto width
      searching: true, // Show search
      bInfo: true, // Info at footer
      bSort: true, // Sorting for column

    }); {% endcomment %}


    $(document).ready(function() {
    console.log('DataTable Ready')
    $("#rowcount").html($(".filterable tr").length - 1);
  
    // Add a click event listener to the .btn-filter element
    $("#FilterON").click(function() {
      var table = $(this).parents(".filterable");
      var filters = table.find(".filters input");
      var tbody = table.find(".table tbody");
      console.log('DataTable On click ' + table.length + filters.length + tbody.length)
      if (filters.prop("disabled")) {
        // If filters are disabled, enable them and focus on the first input field
        filters.prop("disabled", false);
        filters.first().focus();
      } else {
        // If filters are enabled, clear them and disable them
        filters.val("").prop("disabled", true);
        tbody.find(".no-result").remove();
        tbody.find("tr").show();
      }
  
      // Update the value of #rowcount to reflect the number of rows in the table
      $("#rowcount").html($(".filterable tr").length - 1);
    });
  
    // Listen for keyup events on the filter input fields
    $(".filterable .filters input").keyup(function(event) {
      // Ignore the Tab key
      if (event.keyCode === 9) return;
  
      var input = $(this);
      var value = input.val().toLowerCase();
      var table = input.parents(".filterable");
      var column = table.find(".filters th").index(input.parents("th"));
      var tbody = table.find(".table tbody");
      var rows = tbody.find("tr");
      var matches = rows.filter(function() {
        return $(this).find("td").eq(column).text().toLowerCase().indexOf(value) !== -1;
      });
  
      // Hide rows that don't match the search term and show rows that do match
      rows.hide();
      matches.show();
  
      // If there are no matching rows, add a "No result found" message to the table
      if (matches.length === 0) {
        tbody.prepend('<tr class="no-result text-center"><td colspan="' + table.find(".filters th").length + '">No result found</td></tr>');
      } else {
        tbody.find(".no-result").remove();
      }
  
      // Update the value of #rowcount to reflect the number of visible rows in the table
      $("#rowcount").html(rows.filter(":visible").length - 1);
  
      // Call the checkval() function
      checkval();
    });
  });
  
  // Define the checkval() function
  function checkval() {
    var visibleRows = $("tbody tr:visible").length;
    var message = visibleRows === 1 ? "No result found" : visibleRows - 1;
    $("#rowcount").html(message);
  };
             
             
</script>

{% endblock %}

core/templates/update_data/edit_module.html
{% extends "base/base.html" %}

{% block content %}
    <h1>Edit Module</h1>
    <form method="post">
        {% csrf_token %}
        <table class="table">
            <thead>
                <tr>
                    <th>Equipment Code</th>
                    <th>Code</th>
                    <th>Component Description</th>
                    <th>Function Purpose</th>
                    <th>Device Type</th>
                    <th>Signal Type</th>
                    <th>Remarks</th>
                    <th>Segment</th>
                    <th>Initial State</th>
                    <th>Location</th>
                    <th>Update</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for signal in signals %}
                    <tr>
                        <td>{{ signal.equipment_code }}</td>
                        <td>{{ signal.code }}</td>
                        <td>{{ signal.component_description }}</td>
                        <td>{{ signal.function_purpose }}</td>
                        <td>{{ signal.device_type }}</td>
                        <td>{{ signal.signal_type }}</td>
                        <td>{{ signal.remarks }}</td>
                        <td>{{ signal.segment }}</td>
                        <td>{{ signal.initial_state }}</td>
                        <td>{{ signal.location }}</td>
                        <td>
                            <button type="submit" formaction="{% url 'signals' signal.id 'edit'  %}" class="btn btn-primary">Update</button>
                        </td>
                        <td>
                            <button type="submit" formaction="{% url 'signal_delete' signal.id %}" class="btn btn-danger">Delete</button>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        
    </form>


{% endblock %}

core/templates/update_data/edit_signal.html
{% extends 'base/base.html' %}
{% block title %}<title>{{ module }} Edit</title>{% endblock %}
{% block content %}
{% load widget_tweaks %}


  <div class="row  ">
    <div class="col-md-12 ">
      <div class="wrapper ">
        <div class="row justify-content-center">
          <div class="col-lg-8 col-md-7 order-md-last d-flex align-items-stretch">
            <div class="contact-wrap w-100 p-md-5 p-4">
              <div class="panel-heading d-flex align-items-center">
                </button>
                <div class="text-center mx-auto">
                    <h2 class="card-title mt-3">{{ module }}</h2>
                    <h4 class="card-text">{{ module.description }}</h4>
                </div>
            </div>


<form method="POST" id="iolistForm" name="iolistForm" class="iolistForm" novalidate="novalidate">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            {% comment %} <label for="id_project">Project:</label> {% endcomment %}
            <label class="label" for="{{ form.equipment_code.id_for_label }}">{{ form.equipment_code.label_tag }}</label>
            {{form.equipment_code}} 
          </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <label class="label" for="{{ form.code.id_for_label }}">{{ form.code.label_tag }}</label>
              
              {% render_field form.code|add_class:"form-control"  %}
      
            </div>
          </div>
      <div class="col-md-6">
        <div class="form-group">
          <label class="label" for="{{ form.component_description.id_for_label }}">{{ form.component_description.label_tag }}</label>
          {% render_field form.component_description|add_class:"form-control" %}
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <label class="label" for="{{ form.function_purpose.id_for_label }}">{{ form.function_purpose.label_tag }}</label>
          {% render_field form.function_purpose|add_class:"form-control" %}
  
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <label class="label" for="{{ form.signal_type.id_for_label }}">{{ form.signal_type.label_tag }}</label>
          {% render_field form.signal_type|add_class:"form-control" %}
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <label class="label" for="{{ form.device_type.id_for_label }}">{{ form.device_type.label_tag }}</label>
          {% render_field form.device_type|add_class:"form-control" %}
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <label class="label" for="{{ form.location.id_for_label }}">{{ form.location.label_tag }}</label>
          {% render_field form.location|add_class:"form-control" %}
        </div>
      </div>
      {% comment %} <div class="col-md-6">
        <div class="form-group">
          <label class="label" for="{{ form.module.id_for_label }}">{{ form.module.label_tag }}</label>
          {% render_field form.module|add_class:"form-control" %}
        </div>
      </div> {% endcomment %}
      <div class="col-md-6">
        <div class="form-group">
          <label class="label" for="{{ form.initial_state.id_for_label }}">{{ form.initial_state.label_tag }}</label>
          {% render_field form.initial_state|add_class:"form-control" %}
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <label class="label" for="{{ form.Demo_3d_Property.id_for_label }}">{{ form.Demo_3d_Property.label_tag }}</label>
          {% render_field form.Demo_3d_Property|add_class:"form-control" %}
        </div>
      </div>



                 <div class="col-md-12">
                    <div class="form-group">
                      <input type="submit" value="Update Signal" class="btn btn-warning">
                      {% comment %} <a href="{% url 'edit_module' module_id=module.id %}" class="btn float-none btn-info">Cancel</a>  {% endcomment %}
                      <a href="{% url 'signals' signal.id 'delete' %}" class="btn float-right btn-info">Cancel</a> 
                      <div class="submitting"></div>
                    </div>
                  </div>
                </div>
              </form>


          </div>
        </div>
    </div>
</div>
</div>
</div>

 {% endblock %}

core/templates/update_data/form_module.html
{% extends 'base/base.html' %}
{% block title %}<title>Create New Cluster</title>{% endblock %}
{% block content %}
{% load widget_tweaks %}


  <div class="row  ">
    <div class="col-md-12 ">
      <div class="wrapper ">
        <div class="row justify-content-center">
          <div class="col-lg-8 col-md-7 order-md-last d-flex align-items-stretch">
            <div class="contact-wrap w-100 p-md-5 p-4">
              <div class="panel-heading d-flex align-items-center">
                </button>
                <div class="text-center mx-auto">
                    <h2 class="card-title mt-3">{{ module }}</h2>
                    <h4 class="card-text">{{ module.description }}</h4>
                </div>
            </div>


<form method="POST" id="iolistForm" name="iolistForm" class="iolistForm" novalidate="novalidate">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            {% comment %} <label for="id_project">Project:</label> {% endcomment %}
            <label class="label" for="{{ form.module.id_for_label }}">{{ form.module.label_tag }}</label>
            {% render_field form.module|add_class:"form-control"  %}
          </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <label class="label" for="{{ form.segment.id_for_label }}">{{ form.segment.label_tag }}</label>
              
              {% render_field form.segment|add_class:"form-control"  %}
      
            </div>
          </div>
      <div class="col-md-6">
        <div class="form-group">
          <label class="label" for="{{ form.description.id_for_label }}">{{ form.description.label_tag }}</label>
          {% render_field form.description|add_class:"form-control" %}
        </div>
      </div>

      
        {% if messages %}
        {% for message in messages%}
        <h2 class= "text-danger text-center" >{{message}}</h2>
        {% endfor %}
        {% endif %}

                 <div class="col-md-12">
                    <div class="form-group">
                      <input type="submit" value="Add Module" class="btn btn-success">
                      <a href="{% url 'module_list'  %}" class="btn float-right btn-danger">Cancel</a> 
                      <div class="submitting"></div>
                    </div>
                  </div>
                </div>
              </form>


          </div>
        </div>
    </div>
</div>
</div>
</div>

 {% endblock %}

core/templates/update_data/update_module.html
{% extends "base/base.html" %}
{% block styles %}
<style>
  Cluster{
    background-color: rgb(211, 192, 48);
    font-weight: bold;
    font-size: medium;
  }
  Cluster:hover{
    background-color: rgb(39, 86, 95);
  }
</style>
{% endblock %}
{% block title %}<title>Edit Clusters</title>{% endblock %}
{% block content %}
<div id="create-module" >





  <div>
    <div class="panel-heading d-flex align-items-center">
      <button class="btn btn-primary mt-3 mybtns mr-auto" id="FilterON">
          <span class="glyphicon glyphicon-filter"></span>Click To Apply Filter
      </button>
      <a href="{% url 'create_module'  %}" class="btn mt-3 ml-auto mybtns btn-block btn-secondary">Add New Cluster</a>

  </div>
  <table class="table table-striped">
    <thead>
      <tr>
            <th>ID</th>
            <th>Cluster Name</th>
            <th>Segment</th>
            <th>Created By</th>
            <th>Edit</th>
            <th>Delete</th>
          </tr>
        </thead>
        <tbody>
          {% for module in modules %}
          <tr>
            <td>{{ module.id }}</td>
            <td class="Cluster"   >{{ module.module }}</td>
            <td class="Segment"   >{{ module.segment }}</td>
            <td class=""   >{{ module.created_by }}</td>
            <td><button class="button btn-warning" 
              onclick= "location.href='{% url 'edit_module' module_id=module.id  %}'"> Edit Cluster</button>
          </td>
            <td>
                <button class="button btn-danger"  
                data-confirm="Are you sure you want to delete this module?" 
                onclick= "location.href='{% url 'module_delete' id=module.id %}'">Delete Cluster</button>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>

  {% endblock %}